# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_id', models.CharField(max_length=60)),
                ('user_access_token', models.CharField(max_length=150)),
                ('user_access_secret', models.CharField(max_length=150)),
            ],
        ),
    ]
